name: Build and Push to Docker Hub

on:
  workflow_dispatch:  
  #schedule:
  #  - cron: '0 2 * * *'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vnpy:latest

      - name: Verify pushed image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vnpy:latest
